var mydata = angular.module('mydata',[]);

mydata.factory('oriData',function(){
	return [
		{
			demoName:'html5-audio',
			indexDirectName:"html5-audio",
			imageName:"html5-audio.PNG"

		},
		{
			demoName:'wxtk',
			indexDirectName:"wxtk",
			imageName:"wxtk.PNG"
		},
		{
			demoName:'image-show-box',
			indexDirectName:"image-show-box",
			imageName:"image-show-box.PNG"
		},
		{
			demoName:'responsive-test',
			indexDirectName:"responsive-test",
			imageName:"responsive-test.PNG"
		},
		{
			demoName:'tab-c',
			indexDirectName:"tab-c",
			imageName:"tab-c.PNG"
		},
		{
			demoName:'pic-mouse-hover-new',
			indexDirectName:"pic-mouse-hover-new",
			imageName:"pic-mouse-hover-new.PNG"
		},
		{
			demoName:'css3-bowen',
			indexDirectName:"css3-bowen",
			imageName:"css3-bowen.PNG"
		},
		{
			demoName:'css3-transition',
			indexDirectName:"css3-transition",
			imageName:"css3-transition.PNG"
		},
		{
			demoName:'canvas-timer',
			indexDirectName:"canvas-timer",
			imageName:"canvas-timer.PNG"
		}
	]
});