var articleData = {
	'spaceCount':10,
	'canChoiseWordCount':15,
	'canChoiseWords':[
						"common",
						"results",
						"consequently",
						"basis",
						"detection",
						"monitor",
						"symbols",
						"average",
						"dramatically",
						"symptoms",
						"reason",
						"distributed",
						"including",
						"developing",
						"shared"
					],
	'answer':[
				"developing",
				"average",
				"dramatically",
				"results",
				"shared",
				"basis",
				"monitor",
				"including",
				"detection",
				"symptoms"
			],
	'explain':['解析1','解析2','解析3','解析4','解析5','解析6','解析7','解析8','解析9','解析10'],
	'paperContent':'<p>It\'s the first question parents ask when their child is diagnosed with autism (自闭症). Will his future brothers or sisters have a higher risk of 1 <span class="youWord" id="youWord1">&nbsp;</span> it, too? According to the largest study of siblings (兄弟姐妹) in families with autism, the answer is yes. Among 664 children who had at least one older sibling with the developmental disorder, the 2 <span class="youWord" id="youWord2">&nbsp;</span> risk of autism was nearly 19%, 3 <span class="youWord" id="youWord3">&nbsp;</span> higher than previous sibling-recurrence estimates that were anywhere from 3% to 10%. Kids with more than one older autistic sibling had an even higher risk of the disorder: 32%. </p><p>The 4 <span class="youWord" id="youWord4">&nbsp;</span> suggest that genes play a key role in autism risk. But they also hint that other environmental factors 5 <span class="youWord" id="youWord5">&nbsp;</span> by siblings, like influences in the womb (子宫), may be important as well. On the 6 <span class="youWord" id="youWord6">&nbsp;</span> of the findings, the researchers recommend that doctors closely 7 <span class="youWord" id="youWord7">&nbsp;</span> younger siblings of autistic children to pick up any early signs of the disorder, 8 <span class="youWord" id="youWord8">&nbsp;</span> an unusually large head or delayed language development and communication skills. Evidence suggests that early 9<span class="youWord" id="youWord9">&nbsp;</span> and diagnosis of autism can help children take advantage of therapies that can treat some of its 10<span class="youWord" id="youWord10">&nbsp;</span></p>'
}